# Generated by Django 5.0.4 on 2025-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='recipient',
            field=models.TextField(),
        ),
    ]
