# Generated by Django 5.0.4 on 2025-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0002_alter_scheduledemail_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='recipient',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='recipients',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
